version: '3'

services:
  php:
    build: ./docker/php/
    container_name: ${APP_NAME}_php
    volumes:
      - ./:/var/www/html
    ports:
      - 9000:9000
  nginx:
    image: nginx:stable-alpine
    container_name: ${APP_NAME}_nginx
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:rw
      - ./docker/logs/nginx:/var/logs/nginx:rw
    depends_on:
      - php